name: Bike Sharing Rental CICD

on:
  push:
    branches:
      - main  # Runs workflow on every push to the main branch

jobs:
  train_model:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install -r requirements/requirements.txt

      - name: Train the Model
        run: |
          python bikeshare_model/train_pipeline.py  # Change path as per your project structure

  test_model:
    runs-on: ubuntu-latest
    needs: train_model  # Runs after model training
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install -r requirements/requirements.txt

      - name: Run Tests
        run: |
          pytest  # Runs unit tests

  build_package:
    runs-on: ubuntu-latest
    needs: [train_model, test_model]  # Runs after tests pass
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Build Tools
        run: |
          pip install build

      - name: Build the Package
        run: |
          python -m build  # Creates .whl and .tar.gz files

  dockerize_api:
    runs-on: ubuntu-latest
    needs: build_package  # Runs after package is built
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_dckr_pat_WhuJOqm3yCj8PNp34mqZTPBtRRo }}" | docker login -u "${{ secrets.DOCKER_prakum14 }}" --password-stdin

      - name: Build and Tag Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_prakum14 }}/bike_sharing_api:latest -f bikeshare_model_api/Dockerfile .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_prakuma14 }}/bike_sharing_api:latest
